# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/dsplab/TEST_CODE_ANGLE_CALCULATE/TEST_CODE_ANGLE_CALCULATE.cache/wt [current_project]
set_property parent.project_path /home/dsplab/TEST_CODE_ANGLE_CALCULATE/TEST_CODE_ANGLE_CALCULATE.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_vhdl -library xil_defaultlib {
  /home/dsplab/TEST_CODE_ANGLE_CALCULATE/TEST_CODE_ANGLE_CALCULATE.srcs/sources_1/new/sv.vhd
  /home/dsplab/TEST_CODE_ANGLE_CALCULATE/TEST_CODE_ANGLE_CALCULATE.srcs/sources_1/new/asdfas.vhd
  /home/dsplab/TEST_CODE_ANGLE_CALCULATE/TEST_CODE_ANGLE_CALCULATE.srcs/sources_1/new/ad.vhd
  /home/dsplab/TEST_CODE_ANGLE_CALCULATE/TEST_CODE_ANGLE_CALCULATE.srcs/sources_1/new/MAIN.vhd
}
read_xdc /home/dsplab/TEST_CODE_ANGLE_CALCULATE/TEST_CODE_ANGLE_CALCULATE.srcs/constrs_1/new/new.xdc
set_property used_in_implementation false [get_files /home/dsplab/TEST_CODE_ANGLE_CALCULATE/TEST_CODE_ANGLE_CALCULATE.srcs/constrs_1/new/new.xdc]

synth_design -top MAIN -part xc7a100tcsg324-1
write_checkpoint -noxdef MAIN.dcp
catch { report_utilization -file MAIN_utilization_synth.rpt -pb MAIN_utilization_synth.pb }
