# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/dsplab/angle_accel/angle_accel.srcs/sources_1/ip/sqrt/sqrt.xci
# IP: The module: 'sqrt' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/dsplab/angle_accel/angle_accel.srcs/sources_1/ip/sqrt/sqrt_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sqrt'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /home/dsplab/angle_accel/angle_accel.srcs/sources_1/ip/sqrt/sqrt.xci
# IP: The module: 'sqrt' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/dsplab/angle_accel/angle_accel.srcs/sources_1/ip/sqrt/sqrt_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sqrt'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
