set_property PACKAGE_PIN K5 [get_ports Check_counter_mod]
set_property PACKAGE_PIN F6 [get_ports Check_counter_mod_diff]
set_property PACKAGE_PIN E3 [get_ports CLK_50_MHz]
set_property PACKAGE_PIN P4 [get_ports ResetN]
set_property PACKAGE_PIN H4 [get_ports SCL]
set_property PACKAGE_PIN G1 [get_ports SDA]
set_property PACKAGE_PIN L16 [get_ports WokeUp]
set_property IOSTANDARD LVCMOS33 [get_ports Check_counter_mod]
set_property IOSTANDARD LVCMOS33 [get_ports Check_counter_mod_diff]
set_property IOSTANDARD LVCMOS33 [get_ports CLK_50_MHz]
set_property IOSTANDARD LVCMOS33 [get_ports ResetN]
set_property IOSTANDARD LVCMOS33 [get_ports SCL]
set_property IOSTANDARD LVCMOS33 [get_ports SDA]
set_property IOSTANDARD LVCMOS33 [get_ports WokeUp]




set_property PACKAGE_PIN D4 [get_ports RX_PIN]
set_property IOSTANDARD LVCMOS33 [get_ports RX_PIN]


set_property PACKAGE_PIN H6 [get_ports data_ready]
set_property IOSTANDARD LVCMOS33 [get_ports data_ready]




set_property IOSTANDARD LVCMOS33 [get_ports {DataOut[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DataOut[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DataOut[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DataOut[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DataOut[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DataOut[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DataOut[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DataOut[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DataOut[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DataOut[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DataOut[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DataOut[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DataOut[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DataOut[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DataOut[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DataOut[0]}]
set_property PACKAGE_PIN P2 [get_ports {DataOut[15]}]
set_property PACKAGE_PIN R2 [get_ports {DataOut[14]}]
set_property PACKAGE_PIN U1 [get_ports {DataOut[13]}]
set_property PACKAGE_PIN P5 [get_ports {DataOut[12]}]
set_property PACKAGE_PIN R1 [get_ports {DataOut[11]}]
set_property PACKAGE_PIN V1 [get_ports {DataOut[10]}]
set_property PACKAGE_PIN U3 [get_ports {DataOut[9]}]
set_property PACKAGE_PIN V4 [get_ports {DataOut[8]}]
set_property PACKAGE_PIN U6 [get_ports {DataOut[7]}]
set_property PACKAGE_PIN U7 [get_ports {DataOut[6]}]
set_property PACKAGE_PIN T4 [get_ports {DataOut[5]}]
set_property PACKAGE_PIN T5 [get_ports {DataOut[4]}]
set_property PACKAGE_PIN T6 [get_ports {DataOut[3]}]
set_property PACKAGE_PIN R8 [get_ports {DataOut[2]}]
set_property PACKAGE_PIN V9 [get_ports {DataOut[1]}]
set_property PACKAGE_PIN T8 [get_ports {DataOut[0]}]
